name       : python-uranium
version    : 4.13.1
release    : 31
source     :
    - https://github.com/Ultimaker/Uranium/archive/refs/tags/4.13.1.tar.gz : 185db9e6353a4f44b69287ed5f6314d28f10a0dd43790485275d6db5b5907a41
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A Python framework for building Desktop applications
description: |
    Uranium is a Python framework for building 3D printing related applications.
builddeps  :
    - pkgconfig(geos)
    - libarcus
    - python-pytest
    - python-shapely
    - python-twisted
    - python3-qt5
    - scipy
rundeps    :
    - libarcus
    - python-cryptography
    - python-shapely
    - python3-qt5
    - qt5-quickcontrols
    - qt5-quickcontrols2
    - scipy
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %python3_test py.test3 -v -k "not TestHttpRequestManager"
