name       : python-uranium
version    : 4.4.1
release    : 19
source     :
    - https://github.com/Ultimaker/Uranium/archive/4.4.1.tar.gz : 21cd4938b21fb99be19f5eee4c6e1a4d554e8ebd5b3be2998abe0a1a6f9ffc39
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A Python framework for building Desktop applications
description: |
    Uranium is a Python framework for building 3D printing related applications.
builddeps  :
    - libarcus
    - python-pytest
    - python-shapely
    - python3-qt5
    - scipy
rundeps    :
    - libarcus
    - python-shapely
    - python3-qt5
    - qt5-quickcontrols
    - qt5-quickcontrols2
    - scipy
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    # pytest-benchmark is required for test_setLockedAxis
    %python3_test py.test3 -v -k 'not test_setLockedAxis'
