name       : python-uranium
version    : 4.6.2
release    : 21
source     :
    - https://github.com/Ultimaker/Uranium/archive/4.6.2.tar.gz : 8f162f7e31681eca198e59d0a6a9382ad82527729e6f9981d8e75ce7671c05d5
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A Python framework for building Desktop applications
description: |
    Uranium is a Python framework for building 3D printing related applications.
builddeps  :
    - libarcus
    - python-pytest
    - python-shapely
    - python-twisted
    - python3-qt5
    - scipy
rundeps    :
    - libarcus
    - python-cryptography
    - python-shapely
    - python3-qt5
    - qt5-quickcontrols
    - qt5-quickcontrols2
    - scipy
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %python3_test py.test3 -v -k "not TestHttpRequestManager"
