name       : python-uranium
version    : 3.4.1
release    : 7
source     :
    - https://github.com/Ultimaker/Uranium/archive/3.4.1.tar.gz : 7a97385b101a30008d1c0bb576d603b93ca2d0967b8c71faeb6760c9cc9ecb72
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A Python framework for building Desktop applications
description: |
    Uranium is a Python framework for building 3D printing related applications.
builddeps  :
    - libarcus
    - python-pytest
    - python3-qt5
    - scipy
rundeps    :
    - libarcus
    - python3-qt5
    - qt5-quickcontrols
    - scipy
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    pip3 freeze
    python3 -m pytest -v -k "not TestContainerStack and not test_addContainerType and not test_uniqueName"
