name       : python-uranium
version    : 4.0.0
release    : 11
source     :
    - https://github.com/Ultimaker/Uranium/archive/4.0.0.tar.gz : d405183b98b2e8db8c8c11ebe6f8838865cb4ac7f6a55ab0ac654b060edf9dd8
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A Python framework for building Desktop applications
description: |
    Uranium is a Python framework for building 3D printing related applications.
builddeps  :
    - libarcus
    - python-pytest
    - python-shapely
    - python3-qt5
    - scipy
rundeps    :
    - libarcus
    - python-shapely
    - python3-qt5
    - qt5-quickcontrols
    - qt5-quickcontrols2
    - scipy
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %python3_test py.test3 -v
