name       : python-uranium
version    : 2.7.0
release    : 1
source     :
    - https://github.com/Ultimaker/Uranium/archive/2.7.0.tar.gz : 367a6408413bd5cfd8121745f2ae0d855ac0895c7c14326bfd4c9227223ed87b
license    : LGPL-2.0
component  : programming.python
summary    : A Python framework for building Desktop applications
description: |
    Uranium is a Python framework for building 3D printing related applications.
rundeps    :
    - libarcus
    - numpy
    - python3-qt5
    - qt5-quickcontrols
setup      : |
    sed -i 's|lib/python${PYTHON_VERSION_MAJOR}/dist-packages|lib/python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}/site-packages|g' CMakeLists.txt
    %cmake .
build      : |
    %make
install    : |
    %make_install
