name       : python-uranium
version    : 4.10.0
release    : 26
source     :
    - https://github.com/Ultimaker/Uranium/archive/4.10.0.tar.gz : e72942b9e24ba0855f8a1184220a57e4af8a4ebcb8ced27973c18bfb1777d737
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A Python framework for building Desktop applications
description: |
    Uranium is a Python framework for building 3D printing related applications.
builddeps  :
    - libarcus
    - python-pytest
    - python-shapely
    - python-twisted
    - python3-qt5
    - scipy
rundeps    :
    - libarcus
    - python-cryptography
    - python-shapely
    - python3-qt5
    - qt5-quickcontrols
    - qt5-quickcontrols2
    - scipy
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %python3_test py.test3 -v -k "not TestHttpRequestManager"
