name       : python-uranium
version    : 4.12.0
release    : 28
source     :
    - https://github.com/Ultimaker/Uranium/archive/4.12.0.tar.gz : e0730cae4ad210bbfeba9384ec37ee9e8700ad9c202a6b085f4aa98e564f22be
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A Python framework for building Desktop applications
description: |
    Uranium is a Python framework for building 3D printing related applications.
builddeps  :
    - libarcus
    - python-pytest
    - python-shapely
    - python-twisted
    - python3-qt5
    - scipy
rundeps    :
    - libarcus
    - python-cryptography
    - python-shapely
    - python3-qt5
    - qt5-quickcontrols
    - qt5-quickcontrols2
    - scipy
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %python3_test py.test3 -v -k "not TestHttpRequestManager"
