name       : python-uranium
version    : 3.2.1
release    : 5
source     :
    - https://github.com/Ultimaker/Uranium/archive/3.2.1.tar.gz : 856b0ec8e8c96737464c74294419cc423cbf463c5b19bb61f75ba35750f06d0d
license    : LGPL-2.0
component  : programming.python
summary    : A Python framework for building Desktop applications
description: |
    Uranium is a Python framework for building 3D printing related applications.
builddeps  :
    - libarcus
    - python-pytest
    - python3-qt5
    - scipy
rundeps    :
    - libarcus
    - python3-qt5
    - qt5-quickcontrols2
    - scipy
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    pip3 freeze
    python3 -m pytest -v

