name       : python-uranium
version    : 3.5.1
release    : 8
source     :
    - https://github.com/Ultimaker/Uranium/archive/3.5.1.tar.gz : 488332fd80f07037c735457de2989dc5c9482a4a34de19885f405eb77eccf518
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A Python framework for building Desktop applications
description: |
    Uranium is a Python framework for building 3D printing related applications.
builddeps  :
    - libarcus
    - python-pytest
    - python-shapely
    - python3-qt5
    - scipy
rundeps    :
    - libarcus
    - python-shapely
    - python3-qt5
    - qt5-quickcontrols
    - scipy
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    pip3 freeze
    python3 -m pytest -v -k "not TestContainerStack and not test_addContainerType and not test_uniqueName"
