name       : python-uranium
version    : 4.8.0
release    : 23
source     :
    - https://github.com/Ultimaker/Uranium/archive/4.8.0.tar.gz : 17e292361b7bbd89838599e78e4df2a8e69f247209b38e5098b25f5c83affcf2
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A Python framework for building Desktop applications
description: |
    Uranium is a Python framework for building 3D printing related applications.
builddeps  :
    - libarcus
    - python-pytest
    - python-shapely
    - python-twisted
    - python3-qt5
    - scipy
rundeps    :
    - libarcus
    - python-cryptography
    - python-shapely
    - python3-qt5
    - qt5-quickcontrols
    - qt5-quickcontrols2
    - scipy
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %python3_test py.test3 -v -k "not TestHttpRequestManager"
