name       : python-uranium
version    : 3.0.3
release    : 2
source     :
    - https://github.com/Ultimaker/Uranium/archive/3.0.3.tar.gz : 6021d5843fa0b09c13c41dee1c04a71fa9ff9090fa73f7e0430a77822e621cb1
license    : LGPL-2.0
component  : programming.python
summary    : A Python framework for building Desktop applications
description: |
    Uranium is a Python framework for building 3D printing related applications.
rundeps    :
    - libarcus
    - numpy
    - python3-qt5
    - qt5-quickcontrols
setup      : |
    sed -i 's|lib/python${PYTHON_VERSION_MAJOR}/dist-packages|lib/python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}/site-packages|g' CMakeLists.txt
    %cmake .
build      : |
    %make
install    : |
    %make_install
