name       : python-uranium
version    : 3.1.0
release    : 3
source     :
    - https://github.com/Ultimaker/Uranium/archive/3.1.0.tar.gz : 1d272d10cbb3585624a67cbaa5167d414a0eeeb76051be28786759fea63281e9
license    : LGPL-2.0
component  : programming.python
summary    : A Python framework for building Desktop applications
description: |
    Uranium is a Python framework for building 3D printing related applications.
builddeps  :
    - libarcus
    - python-pytest
    - python3-qt5
    - scipy
rundeps    :
    - libarcus
    - python3-qt5
    - qt5-quickcontrols
    - scipy
setup      : |
    %patch -p1 < $pkgfiles/uranium-3.1.0-fix-broken-test-suite.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    pip3 freeze
    python3 -m pytest -v
